### ISSUE TITLE
Dynamic link error with Android less then 29 API level

### ISSUE THREAD

**Issue by Gordon-F** [timothee-haudebourg/khronos-egl#11]
Test [gfx-quad gl](https://github.com/gfx-rs/gfx) example on Android:

```
2020-12-21 22:38:15.970 9618-9727/rust.quad_android I/RustStdoutStderr: NativeScreen Found:RwLockReadGuard { lock: RwLock { data: Some(NativeWindow { ptr: 0x7d3f1fd010 }) } }
2020-12-21 22:38:15.972 9618-9728/rust.quad_android W/gfx_backend_gl::windo..: Unable to open libEGL.so: DlSym { desc: "undefined symbol: eglGetPlatformDisplay" }
```

eglGetPlatformDisplay only avaliable in API level 29 (Android 10).
https://developer.android.google.cn/reference/android/opengl/EGL15#eglGetPlatformDisplay(int,%20long,%20long[],%20int)

Maybe we can feature-gate egl version api at compile time?

**Comment by timothee-haudebourg** [comment]
Depends... do you always know at compile time what version you are running on?

**Comment by timothee-haudebourg** [comment]
With the `versions` branch you should be able to choose a specific API version at compile time. Can you try it out?

For instance in your case, if you only want to use EGL 1.4, use something like this in your `Cargo.toml`:
```toml
[dependencies.khronos-egl]
git = "https://github.com/timothee-haudebourg/khronos-egl.git"
branch = "versions"
default-features = false
features = ["dynamic", "1.4"] # dynamic loading, up to EGL 1.4
```
then you should be able to use `DynamicInstance` as usual.

Alternatively, you can load a specific version of EGL using the type system:
```rust
use khronos_egl::{Dynamic, Instance, EGL1_4};

let lib = libloading::Library::new(filename)?;
let egl = Instance::new(Dynamic::<_, EGL1_4>::new(lib)?); // only EGL1.4 will be loaded here.
```

You can also write functions for a specific API version, although it may not be that useful until function specialization becomes a thing in Rust:
```rust
use khronos_egl::{Instance, api};

fn foo<V: api::EGL1_4>(egl: &Instance<V>) {
  // do something that requires at least EGL 1.4.
}
```
